#define DX10_BLEND_STATES		DXC_BLEND_RGBA_ONE_ONE_REVSUB;			DXC_DEPTHSTENCIL_ZREAD;
#define DX9_BLEND_STATES		SrcBlend = ONE;		DestBlend = ONE;	BlendOp = REVSUBTRACT;   COLORWRITEENABLE = RED | GREEN | BLUE;
#define ADDITIVE_BLEND			1

#include "Dx9/_Spectral.fxh"

