#define DX10_BLEND_STATES		DXC_BLEND_RGBA_SRCALPHA_INVSRCALPHA_ADD;
#define DX9_BLEND_STATES		SrcBlend = SRCALPHA; DestBlend = INVSRCALPHA;
#define ADDITIVE_BLEND			0

#include "Dx9/_Spectral.fxh"

