#ifndef _ENCODER_DEF_H_
#define _ENCODER_DEF_H_

enum COMPRESSION_TYPE
{
	COMPRESSION_TYPE_NONE, //used for patch server
	COMPRESSION_TYPE_GAME_SERVER_TO_CLIENT,
	COMPRESSION_TYPE_GAME_CLIENT_TO_SERVER,
	COMPRESSION_TYPE_CHAT_SERVER_TO_CLIENT,
	COMPRESSION_TYPE_CHAT_CLIENT_TO_SERVER,

	COMPRESSION_TYPE_COUNT
};

enum ENCRYPTION_TYPE
{
	ENCRYPTION_TYPE_NONE,
	ENCRYPTION_TYPE_ARC4,
	ENCRYPTION_TYPE_PRNG8,
//	ENCRYPTION_TYPE_PRNG32,
//	ENCRYPTION_TYPE_SALSA20_8
	ENCRYPTION_TYPE_LAST //Not a valid type :)
};

#endif //_ENCODER_DEF_H_