//----------------------------------------------------------------------------
// FILE: fontcolor.h
//
// (C)Copyright 2006, Flagship Studios. All rights reserved.
//----------------------------------------------------------------------------

#ifndef __FONTCOLOR_H_
#define __FONTCOLOR_H_

//----------------------------------------------------------------------------
// INCLUDES
//----------------------------------------------------------------------------
#include "../data_common/excel/fontcolor_hdr.h"  // auto generated by fontcolor.xls

#endif  // end __FONTCOLOR_H_