//----------------------------------------------------------------------------
// gameglobals.h
//
// (C)Copyright 2003, Flagship Studios. All rights reserved.
//----------------------------------------------------------------------------
#ifndef _GAMEGLOBALS_H_
#define _GAMEGLOBALS_H_


//----------------------------------------------------------------------------
// STRUCTS
//----------------------------------------------------------------------------
struct GAME_GLOBALS_DATA
{
	EXCEL_STR		(szName);								// key
	int				nIntValue;
	float			fFloatValue;
};


//----------------------------------------------------------------------------
// enum
//----------------------------------------------------------------------------
enum GAME_GLOBALS
{
#undef	GAME_GLOBAL_DEF
#define GAME_GLOBAL_DEF(e, t, i)			GAME_GLOBAL_##e = i,
#include "..\data_common\excel\gameglobals_hdr.h"	// auto-generated by gameglobals.xls
};


//----------------------------------------------------------------------------
// global extern
//----------------------------------------------------------------------------
#undef  GAME_GLOBAL_DEF
#define GAME_GLOBAL_DEF(e, t, i)			extern t e;
#include "..\data_common\excel\gameglobals_hdr.h"	// auto-generated by gameglobals.xls


//----------------------------------------------------------------------------
// EXPORTS
//----------------------------------------------------------------------------
BOOL ExcelGameGlobalsPostProcess(
	struct EXCEL_TABLE * table);


#endif // _GAMEGLOBALS_H_