//----------------------------------------------------------------------------
// gameglobals.cpp
// 
// (C)Copyright 2003, Flagship Studios. All rights reserved.
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
// INCLUDE
//----------------------------------------------------------------------------

#include "excel.h"
#include "excel_private.h"
#include "gameglobals.h"


//----------------------------------------------------------------------------
// GLOBALS
//----------------------------------------------------------------------------
#undef  GAME_GLOBAL_DEF
#define GAME_GLOBAL_DEF(e, t, i)			t e;
#include "..\data_common\excel\gameglobals_hdr.h"	// auto-generated by gameglobals.xls


//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
// gameglobals.txt
EXCEL_STRUCT_DEF(GAME_GLOBALS_DATA)
	EF_DSTRING(		"Name",									szName																				)
	EF_INT(			"int_value",							nIntValue																			)	
	EF_FLOAT(		"float_value",							fFloatValue																			)		
	EXCEL_SET_INDEX(0, EXCEL_INDEX_WARN_DUPLICATE, "Name")
	EXCEL_SET_POSTPROCESS_TABLE(ExcelGameGlobalsPostProcess)
EXCEL_STRUCT_END
EXCEL_TABLE_DEF(DATATABLE_GAME_GLOBALS, GAME_GLOBALS_DATA, APP_GAME_ALL, EXCEL_TABLE_SHARED, "gameglobals") EXCEL_TABLE_END


//----------------------------------------------------------------------------
// EXPORTED FUNCTIONS
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
BOOL ExcelGameGlobalsPostProcess(
	EXCEL_TABLE * table)
{
	#undef  GAME_GLOBAL_DEF
	#define GAME_GLOBAL_DEF(e, t, i)		{ const GAME_GLOBALS_DATA * global_data = (const GAME_GLOBALS_DATA *)ExcelGetDataPrivate(table, i);  if (global_data) { if (#t[0] == 'f') { e = (t)global_data->fFloatValue; } else { e = (t)global_data->nIntValue; } } }
	#include "..\data_common\excel\gameglobals_hdr.h"	// auto-generated by gameglobals.xls

	return TRUE;
}
