//----------------------------------------------------------------------------
// FILE: globalindex.h
//
// (C)Copyright 2005, Flagship Studios. All rights reserved.
//----------------------------------------------------------------------------
#ifndef __GLOBALINDEX_H_
#define __GLOBALINDEX_H_


//----------------------------------------------------------------------------
// Forward References
//----------------------------------------------------------------------------
struct GAME;
enum EXCELTABLE;

#include "..\data_common\excel\globalindex_hdr.h"	// auto-generated by globalindex.xls
#include "..\data_common\excel\globalstring_hdr.h"	// auto-generated by globalindex.xls


//----------------------------------------------------------------------------
// Types
//----------------------------------------------------------------------------
#define GLOBAL_INDEX_ENTRY_NAME_SIZE 64
struct GLOBAL_INDEX_ENTRY
{
	char pszName[GLOBAL_INDEX_ENTRY_NAME_SIZE];
	char pszString[MAX_XML_STRING_LENGTH];
	char pszTugboatString[MAX_XML_STRING_LENGTH];
	EXCELTABLE eDataTable;
	int nIndex;
	SAFE_PTR(const WCHAR*, puszString);
};


//----------------------------------------------------------------------------
// Function Prototypes
//----------------------------------------------------------------------------
int GlobalIndexGet(
	GLOBAL_INDEX eGlobalIndex);

const char *GlobalIndexGetName(
	GLOBAL_INDEX eGlobalIndex);

EXCELTABLE GlobalIndexGetDatatable(
	GLOBAL_INDEX eGlobalIndex);

void GlobalIndexValidate(
	void);

const WCHAR *GlobalStringGet(
	GLOBAL_STRING eGlobalString);

const WCHAR *GlobalStringGetEx(
	GLOBAL_STRING eGlobalString,
	const WCHAR * pDefault);

const char *GlobalStringGetKey(
	GLOBAL_STRING eGlobalString);

int GlobalStringGetStringIndex(
	GLOBAL_STRING eGlobalString);
	
BOOL GlobalIndexExcelPostProcess( 
	struct EXCEL_TABLE * table);

BOOL GlobalStringCacheStrings(
	void);

INT_PTR GlobalStringMessageBox(
	HWND hWnd,
	GLOBAL_STRING eText,
	GLOBAL_STRING eCaption,
	UINT uType,
	...);
	
#endif  // end __GLOBALINDEX_H_
