//----------------------------------------------------------------------------
// dxC_effect_def.h
//
// - Header for effect params
//
// (C)Copyright 2003, Flagship Studios. All rights reserved.
//----------------------------------------------------------------------------

#ifdef INCLUDE_EFFECTPARAM_ENUM
#define DEFINE_PARAM(codename,fxname) codename,
#else
#define DEFINE_PARAM(codename,fxname) fxname,
#endif


DEFINE_PARAM( EFFECT_PARAM_BRANCH_SPECULAR,					"gbSpecular"							 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_NORMALMAP,				"gbNormalMap"							 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_DIFFUSEMAP2,				"gbDiffuseMap2"							 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_LIGHTMAP,					"gbLightMap"							 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_SHADOWMAP,				"gbShadowMap"							 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_SHADOWMAPDEPTH,			"gbShadowMapDepth"						 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_DEBUGFLAG,				"gbDebugFlag"							 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_CUBE_ENVMAP,				"gbCubeEnvironmentMap"					 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_SPHERE_ENVMAP,			"gbSphereEnvironmentMap"				 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_SKINNED,					"gbSkinned"								 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_DIRLIGHT,					"gbDirectionalLight"					 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_DIRLIGHT2,				"gbDirectionalLight2"					 )
DEFINE_PARAM( EFFECT_PARAM_BRANCH_SCROLLLIGHTMAP,			"gbScrollLightmap"						 )
// if adding branch, update branch validation combinations as well as MAX_MUST_HAVE_EFFECT_PARAM
DEFINE_PARAM( EFFECT_PARAM_WORLDVIEWPROJECTIONMATRIX,		"WorldViewProjection"					 )
DEFINE_PARAM( EFFECT_PARAM_WORLDVIEWPROJECTIONMATRIX_PREV,	"WorldViewProjectionPrev"				 )
DEFINE_PARAM( EFFECT_PARAM_WORLDMATRIX,						"World"									 )
DEFINE_PARAM( EFFECT_PARAM_VIEWMATRIX,						"View"									 )
DEFINE_PARAM( EFFECT_PARAM_VIEWPROJECTIONMATRIX,			"ViewProjection"						 )
DEFINE_PARAM( EFFECT_PARAM_FOGDISTANCEMAX,					"FogMaxDistance"						 )
DEFINE_PARAM( EFFECT_PARAM_FOGDISTANCEMIN,					"FogMinDistance"						 )
DEFINE_PARAM( EFFECT_PARAM_ALPHA_MIN_OPAQUE,				"GLOW_MIN"								 )
DEFINE_PARAM( EFFECT_PARAM_FOGCOLOR,						"FogColor"								 )
DEFINE_PARAM( EFFECT_PARAM_BONES,							"Bones"									 )
DEFINE_PARAM( EFFECT_PARAM_BONES_PREV,						"BonesPrev"								 )
DEFINE_PARAM( EFFECT_PARAM_EYEINOBJECT,						"EyeInObject"							 )
DEFINE_PARAM( EFFECT_PARAM_EYEINWORLD,						"EyeInWorld"							 )
DEFINE_PARAM( EFFECT_PARAM_PIXEL_ACCURATE_OFFSET,			"gvPixelAccurateOffset"					 )	
DEFINE_PARAM( EFFECT_PARAM_SCREENSIZE,						"gvScreenSize"							 )	
DEFINE_PARAM( EFFECT_PARAM_VIEWPORT,						"gvViewport"							 )	
DEFINE_PARAM( EFFECT_PARAM_UV_SCALE,						"gvUVScale"								 )	
DEFINE_PARAM( EFFECT_PARAM_SHADOWSIZE,						"gvShadowSize"							 )

// for lighting
DEFINE_PARAM( EFFECT_PARAM_LIGHTAMBIENT,					"LightAmbient"							 )
DEFINE_PARAM( EFFECT_PARAM_DIRLIGHTDIR_OBJECT,				"_DirLightsDir_0"						 )
DEFINE_PARAM( EFFECT_PARAM_DIRLIGHTDIR_WORLD,				"_DirLightsDir_1"						 )
DEFINE_PARAM( EFFECT_PARAM_DIRLIGHTCOLOR,					"DirLightsColor"						 )
DEFINE_PARAM( EFFECT_PARAM_SPOTLIGHTPOS_OBJECT,				"_SpotLightsPos_0"						 )
DEFINE_PARAM( EFFECT_PARAM_SPOTLIGHTPOS_WORLD,				"_SpotLightsPos_1"						 )
DEFINE_PARAM( EFFECT_PARAM_SPOTLIGHTNORMAL_OBJECT,			"_SpotLightsNormal_0"					 )
DEFINE_PARAM( EFFECT_PARAM_SPOTLIGHTNORMAL_WORLD,			"_SpotLightsNormal_1"					 )
DEFINE_PARAM( EFFECT_PARAM_SPOTLIGHTFALLOFF_OBJECT,			"_SpotLightsFalloff_0"					 )
DEFINE_PARAM( EFFECT_PARAM_SPOTLIGHTFALLOFF_WORLD,			"_SpotLightsFalloff_1"					 )
DEFINE_PARAM( EFFECT_PARAM_SPOTLIGHTCOLOR,					"SpotLightsColor"						 )
DEFINE_PARAM( EFFECT_PARAM_POINTLIGHTCOUNT,					"PointLightCount"						 )
DEFINE_PARAM( EFFECT_PARAM_POINTLIGHTPOS_OBJECT,			"_PointLightsPos_0"						 )
DEFINE_PARAM( EFFECT_PARAM_POINTLIGHTPOS_WORLD,				"_PointLightsPos_1"						 )
DEFINE_PARAM( EFFECT_PARAM_POINTLIGHTFALLOFF_OBJECT,		"_PointLightsFalloff_0"					 )
DEFINE_PARAM( EFFECT_PARAM_POINTLIGHTFALLOFF_WORLD,			"_PointLightsFalloff_1"					 )
DEFINE_PARAM( EFFECT_PARAM_POINTLIGHTCOLOR,					"PointLightsColor"						 )
DEFINE_PARAM( EFFECT_PARAM_SPECULARLIGHTPOS_OBJECT,			"_SpecularLightsPos_0"					 )
DEFINE_PARAM( EFFECT_PARAM_SPECULARLIGHTPOS_WORLD,			"_SpecularLightsPos_1"					 )
DEFINE_PARAM( EFFECT_PARAM_SPECULARLIGHTFALLOFF_OBJECT,		"_SpecularLightsFalloff_0"				 )
DEFINE_PARAM( EFFECT_PARAM_SPECULARLIGHTFALLOFF_WORLD,		"_SpecularLightsFalloff_1"				 )
DEFINE_PARAM( EFFECT_PARAM_SPECULARLIGHTCOLOR,				"SpecularLightsColor"					 )


//Textures: We need to keep these grouped to work around an DX10 issue, see ln 99 of dx10_ShaderReflection.cpp -Kevin
//===================================================================================================
DEFINE_PARAM( EFFECT_PARAM_DIFFUSEMAP0,						"tDiffuseMap"							)
DEFINE_PARAM( EFFECT_PARAM_DIFFUSEMAP1,						"tDiffuseMap2"							)
DEFINE_PARAM( EFFECT_PARAM_LIGHTMAP,						"tLightMap"								)
DEFINE_PARAM( EFFECT_PARAM_NORMALMAP,						"tNormalMap"							)
DEFINE_PARAM( EFFECT_PARAM_SELFILLUMMAP,					"tSelfIllumMap"							)
DEFINE_PARAM( EFFECT_PARAM_SPECULARMAP,						"tSpecularMap"							)
DEFINE_PARAM( EFFECT_PARAM_SHADOWMAP,						"tShadowMap"							)
DEFINE_PARAM( EFFECT_PARAM_SHADOWMAPDEPTH,					"tShadowMapDepth"						)
DEFINE_PARAM( EFFECT_PARAM_PARTICLE_LIGHTMAP,				"tParticleLightMap"						)	// CHB 2007.02.15
DEFINE_PARAM( EFFECT_PARAM_CUBE_ENVMAP,						"tCubeEnvironmentMap"					)
DEFINE_PARAM( EFFECT_PARAM_SPHERE_ENVMAP,					"tSphereEnvironmentMap"					)
//NVST: putting textures here for smoke
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_ZOFFSET,   		"Texture_zOffset"  					    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_COLOR,     		"Texture_color"  					    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_VELOCITY,   		"Texture_velocity"  				    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_PRESSURE,   		"Texture_pressure"  				    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_TEMP1,   	    	"Texture_temp1"  					    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_TEMP3,   	    	"Texture_temp3"  					    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_TEMPV,   	    	"Texture_tempVelocity"				    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_BOXDEPTH,          "Texture_depth"                         )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_OBSTACLES,         "Texture_obstacles"                     )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_SCENE_DEPTH,       "Texture_sceneDepth"                    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_RAYCAST,           "Texture_raycast"                       )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_RAYDATASMALL,      "Texture_raydataSmall"                  )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_EDGEDATA,          "Texture_edgeData"                      )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_DENSITYPATTERN,    "Texture_densityPattern"                )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_VELOCITYPATTERN,   "Texture_velocityPattern"               )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TEXTURE_OBSTACLEPATTERN,   "Texture_obstaclePattern"               )
DEFINE_PARAM( EFFECT_PARAM_RAIN_TEXTUREARRAY,               "Texture_rainTextureArray"              )
DEFINE_PARAM( EFFECT_PARAM_SPECULARLOOKUP,					"tSpecularLookup"						)
DEFINE_PARAM( EFFECT_PARAM_GPUPS_TEXRANDOM,					"gpups_tRandom"							)
//for screen effects
DEFINE_PARAM( EFFECT_PARAM_TEXTURE_MOTION,					"Texture_motion"						)
DEFINE_PARAM( EFFECT_PARAM_SCREENFX_TEXTURE0,				"Texture0"								)
DEFINE_PARAM( EFFECT_PARAM_SCREENFX_TEXTURE1,				"Texture1"								)
DEFINE_PARAM( EFFECT_PARAM_SCREENFX_TEXTURERT,				"TextureRT"								)
DEFINE_PARAM( EFFECT_PARAM_DOF_PARAMS,						"gfDOFParams"							)
DEFINE_PARAM( EFFECT_PARAM_CAM_VELOCITY,					"gvCamVelocity"							)
//===================================================================================================
DEFINE_PARAM( EFFECT_PARAM_SPECULAR_MATERIAL_DATA,			"gvSpecularMaterialData"				 )
DEFINE_PARAM( EFFECT_PARAM_MISC_LIGHTING_DATA,				"gvMiscLightingData"					 )
DEFINE_PARAM( EFFECT_PARAM_MISC_MATERIAL_DATA,				"gvMiscMaterialData"					 )
DEFINE_PARAM( EFFECT_PARAM_ENVMAP_DATA,						"gvEnvironmentMapData"					 )
DEFINE_PARAM( EFFECT_PARAM_SCATTER_COLOR_POWER,				"gvSubsurfaceScatterColorPower"			 )
DEFINE_PARAM( EFFECT_PARAM_SHADOW_MATRIX,					"gmShadowMatrix"						 )
DEFINE_PARAM( EFFECT_PARAM_SHADOW_MATRIX2,					"gmShadowMatrix2"						 )
DEFINE_PARAM( EFFECT_PARAM_SHADOW_VIEWMATRIX,				"gmShadowView"							 )
DEFINE_PARAM( EFFECT_PARAM_SHADOW_PROJECTIONMATRIX,			"gmShadowProjection"					 )
DEFINE_PARAM( EFFECT_PARAM_FOGADDITIVEPARTICLELUM,			"FogAdditiveParticleLum"				 )
DEFINE_PARAM( EFFECT_PARAM_PARTICLEMESH_WORLDS,				"ParticleWorlds"						 )
DEFINE_PARAM( EFFECT_PARAM_PARTICLEMESH_COLORS,				"ParticleColors"						 )
DEFINE_PARAM( EFFECT_PARAM_PARTICLEMESH_GLOWS,				"ParticleGlow"							 )
DEFINE_PARAM( EFFECT_PARAM_PARTICLE_FADEIN,					"ParticleFadeIn"						 )
DEFINE_PARAM( EFFECT_PARAM_PARTICLE_TEXTURE_MATRIX,			"ParticleTextureMatrix"					 )
DEFINE_PARAM( EFFECT_PARAM_PARTICLE_GLOBAL_COLOR,			"ParticleGlobalColor"					 )
DEFINE_PARAM( EFFECT_PARAM_PARTICLE_GLOBAL_GLOW,			"ParticleGlobalGlow"					 )
DEFINE_PARAM( EFFECT_PARAM_FOG_FACTOR,						"gfFogFactor"							 )
DEFINE_PARAM( EFFECT_PARAM_SCROLL_TEXTURES,					"gfScrollTextures"						 )
DEFINE_PARAM( EFFECT_PARAM_SCROLL_ACTIVE,					"gfScrollActive"						 )
DEFINE_PARAM( EFFECT_PARAM_SH_CAR,							"cAr"									 )
DEFINE_PARAM( EFFECT_PARAM_SH_CAG,							"cAg"									 )
DEFINE_PARAM( EFFECT_PARAM_SH_CAB,							"cAb"									 )
DEFINE_PARAM( EFFECT_PARAM_SH_CBR,							"cBr"									 )
DEFINE_PARAM( EFFECT_PARAM_SH_CBG,							"cBg"									 )
DEFINE_PARAM( EFFECT_PARAM_SH_CBB,							"cBb"									 )
DEFINE_PARAM( EFFECT_PARAM_SH_CC,							"cC"									 )
DEFINE_PARAM( EFFECT_PARAM_HEMI_LIGHT_COLORS,				"gvHemisphereLightColors"				 )
DEFINE_PARAM( EFFECT_PARAM_WORLDVIEW,						"WorldView"								 )
DEFINE_PARAM( EFFECT_PARAM_PROJECTIONMATRIX,				"Projection"							 )
DEFINE_PARAM( EFFECT_PARAM_SHADOW_LIGHT_DIR,				"ShadowLightDir"						 )
DEFINE_PARAM( EFFECT_PARAM_SKYBOX_SCROLL_DIFFUSE,			"gvScrollDiffuse"						 )
DEFINE_PARAM( EFFECT_PARAM_SKYBOX_SCROLL_OPACITY,			"gvScrollOpacity"						 )
DEFINE_PARAM( EFFECT_PARAM_SKYBOX_OPACITY_COEF,				"gfOpacityCoef"							 )
DEFINE_PARAM( EFFECT_PARAM_SKYBOX_VISIBILITY_COS,			"gvVisibilityCos"						 )
DEFINE_PARAM( EFFECT_PARAM_LAYER_COLOR,						"gvLayerColor"							 )
DEFINE_PARAM( EFFECT_PARAM_BUG_ANIM_LERP,					"gBugLerp"								)
DEFINE_PARAM( EFFECT_PARAM_BIAS,							"gvBias"								)
DEFINE_PARAM( EFFECT_PARAM_SCALE,							"gvScale"								)
DEFINE_PARAM( EFFECT_PARAM_DEBUG_WORLDMAT,					"WorldMat"								)
DEFINE_PARAM( EFFECT_PARAM_DEBUG_VIEWMAT,					"ViewMat"								)
DEFINE_PARAM( EFFECT_PARAM_DEBUG_PROJMAT,					"ProjMat"								)
//NVST: for smoke simulation and rendeing
DEFINE_PARAM( EFFECT_PARAM_SMOKE_WZO,                       "WidthZOffset"                          )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_WIDTH,                     "SimulationTextureWidth"                )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_HEIGHT,                    "SimulationTextureHeight"               ) 
DEFINE_PARAM( EFFECT_PARAM_SMOKE_RT_WIDTH,                  "RTWidth"                               )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_RT_HEIGHT,                 "RTHeight"                              ) 
DEFINE_PARAM( EFFECT_PARAM_SMOKE_VOLUME_DIM,                "gridDim"                               )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_IMPULSE_CENTER,            "center"                                )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_SMOKE_COLOR,               "splatColor"                            )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_MODULATE,                  "modulate"                              )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_FORWARD,                   "forward"                               )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_RENDER_SCALE,              "renderScale"                           )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_NUMCOLS,                   "cols"                                  )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_IMPULSE_SIZE,              "impulseSize"                           )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_IMPULSE_HEIGHT,            "impulseHeight"                         )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_ZFAR,                      "ZFar"                                  )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_ZNEAR,                     "ZNear"                                 )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_ZFAR_MULT_ZNEAR,           "ZFarMultZNear"                         )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_ZFAR_MINUS_ZNEAR,          "ZFarMinusZNear"                        )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_INVERSEPROJECTIONMATRIX,   "InverseProjection"                     )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_INVERSEWORLDVIEWMATRIX,    "InverseWorldView"                      )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_DENSITY_MODIFIER,          "smokeDensityModifier"                  )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_VELOCITY_MODIFIER,         "smokeVelocityModifier"                 )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_AMBIENT_LIGHT,             "smokeAmbientLight"                     )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_RENDER_THICKNESS,          "smokeThickness"                        )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_MAXGRIDDIM,                "maxGridDim"                            )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_TIMESTEP,                  "timestep"                              )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_DECAY_GRID_DISTANCE,       "decayGridDistance"                     )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_GLOW_MIN_DENSITY,          "glowMinDensity"                        )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_GLOW_COLOR_COMPENSATION,   "glowColorCompensation"                 )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_CONFINEMENT_EPSILON,       "confinementEpsilon"                    )
DEFINE_PARAM( EFFECT_PARAM_SMOKE_MAX_OBSTACLE_HEIGHT,       "maxObstacleHeight"                     )
DEFINE_PARAM( EFFECT_PARAM_DISTANCETOSCREEN_Y,              "distanceToScreenY"                     )
DEFINE_PARAM( EFFECT_PARAM_DISTANCETOSCREEN_X,              "distanceToScreenX"                     )
DEFINE_PARAM( FOCUS_UNIT_POSITIONS_ARRAY,                   "FocusUnitPositionsInGrid"              )
DEFINE_PARAM( FOCUS_UNIT_HEIGHT_AND_RADIUS_ARRAY,           "FocusUnitHeightAndRadiusInGrid"        )
DEFINE_PARAM( FOCUS_UNIT_VELOCITIES_ARRAY,                  "focusUnitVelocities"                   )
DEFINE_PARAM( FOCUS_UNIT_NUM,                               "numFocusUnits"                         )


//NVTL: for Soft Particles
DEFINE_PARAM( EFFECT_PARAM_SOFTPARTICLE_SCALE,              "gSoftParticleScale"                    )
DEFINE_PARAM( EFFECT_PARAM_SOFTPARTICLE_CONTRAST,           "gSoftParticleContrast"                 )

//for GPU particles
DEFINE_PARAM( EFFECT_PARAM_GPUPS_PARAMS,					"gpupsParams"							)

//for screen effects
DEFINE_PARAM( EFFECT_PARAM_SCREENFX_TRANSITION,				"gfTransition"							)
DEFINE_PARAM( EFFECT_PARAM_SCREENFX_FLOATS,					"gfFloats"								)
DEFINE_PARAM( EFFECT_PARAM_SCREENFX_COLOR0,					"gvColor0"								)
DEFINE_PARAM( EFFECT_PARAM_SCREENFX_COLOR1,					"gvColor1"								)

//for automap
DEFINE_PARAM( EFFECT_PARAM_AUTOMAP_COLOR_SAME,				"gvAutomapColorSame"					)
DEFINE_PARAM( EFFECT_PARAM_AUTOMAP_COLOR_SHADOW,			"gvAutomapColorShadow"					)
DEFINE_PARAM( EFFECT_PARAM_AUTOMAP_BAND_WEIGHTS,			"gvBandWeights"							)

// For gamma
DEFINE_PARAM( EFFECT_PARAM_GAMMA_POWER,						"gfGammaPow"							)


#undef DEFINE_PARAM
