//----------------------------------------------------------------------------
// FILE: bookmarks.h
//
// (C)Copyright 2006, Flagship Studios. All rights reserved.
//----------------------------------------------------------------------------

#ifdef __BOOKMARKS_H_
//#pragma message ("    HINT: " __FILE__ " included multiple times in this translation unit")
#else
#define __BOOKMARKS_H_

//----------------------------------------------------------------------------
// Includes
//----------------------------------------------------------------------------
#include "../data_common/excel/bookmarks_hdr.h"			// auto generated by excel

//----------------------------------------------------------------------------
// Forward declarations
//----------------------------------------------------------------------------
struct UNIT_FILE_HEADER;

//----------------------------------------------------------------------------
// Types
//----------------------------------------------------------------------------
struct BOOKMARKS
{
	unsigned int nCursorPos[ NUM_UNIT_BOOKMARKS ];
};

//----------------------------------------------------------------------------
// Prototypes
//----------------------------------------------------------------------------

void BookmarksInit( 
	BOOKMARKS &tBookmarks);

template <XFER_MODE mode>
BOOL SetBookmark( 
	const BOOKMARKS &tBookmarks, 
	UNIT_BOOKMARK eBookmark, 
	XFER<mode> &tXfer,
	unsigned int nBookmarkPosition,
	const UNIT_FILE_HEADER &tHeader);

template BOOL SetBookmark<XFER_SAVE>(const BOOKMARKS &, UNIT_BOOKMARK, XFER<XFER_SAVE> &, unsigned int, const UNIT_FILE_HEADER &);
template BOOL SetBookmark<XFER_LOAD>(const BOOKMARKS &, UNIT_BOOKMARK, XFER<XFER_LOAD> &, unsigned int, const UNIT_FILE_HEADER &);


template <XFER_MODE mode>
BOOL BookmarksXfer(
	UNIT_FILE_HEADER &tHeader,
	BOOKMARKS &tBookmarks,
	XFER<mode> &tXfer);

template BOOL BookmarksXfer<XFER_SAVE>(UNIT_FILE_HEADER &, BOOKMARKS &, XFER<XFER_SAVE> & xfer);
template BOOL BookmarksXfer<XFER_LOAD>(UNIT_FILE_HEADER &, BOOKMARKS &, XFER<XFER_LOAD> & xfer);


#endif