#include "importdefines.h"


IMPORT_FUNC(VMCraftingGetSkillLvlParent, RETVAL_INT, CraftingGetParentSkillLvl )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, nParentSkill)
IMPORT_END

IMPORT_FUNC(VMCraftingAddAffixes, RETVAL_INT, CraftingAddAffixes)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp)
IMPORT_END

IMPORT_FUNC(VMCraftingAddDmgType, RETVAL_INT, CraftingAddDmgType)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_DAMAGETYPES, nDamageType ),
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp),
	IMPORT_INDEX(DATATABLE_STATES, nState)
IMPORT_END

IMPORT_FUNC(VMCraftingAddResDmgType, RETVAL_INT, CraftingAddResDmgType)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_DAMAGETYPES, nDamageType ),
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp)
IMPORT_END

IMPORT_FUNC(VMCraftingModifyQuality, RETVAL_INT, CraftingModifyQuality)
	IMPORT_CONTEXT,  
	IMPORT_INT(nModAmount)	
IMPORT_END

IMPORT_FUNC(VMCraftingModifyAttackSpeed, RETVAL_INT, CraftingModifyAttackSpeed)
	IMPORT_CONTEXT,  
	IMPORT_INT(nModAmount)	
IMPORT_END

IMPORT_FUNC(VMCraftingModifyDamage, RETVAL_INT, CraftingModifyDamage)
	IMPORT_CONTEXT,  
	IMPORT_INT(nModAmount)	
IMPORT_END

IMPORT_FUNC(VMCraftingModifyDuration, RETVAL_INT, CraftingModifyDuration)
	IMPORT_CONTEXT,  
	IMPORT_INT(nModAmount)	
IMPORT_END



IMPORT_FUNC(VMCraftingModifyModLevel, RETVAL_INT, CraftingModifyModLevel)
	IMPORT_CONTEXT,  
	IMPORT_INT(nModAmount),
	IMPORT_INT(nValueAmount)
IMPORT_END

IMPORT_FUNC(VMCraftingModifyAC, RETVAL_INT, CraftingModifyAC)
	IMPORT_CONTEXT,  
	IMPORT_INT(nModAmount)	
IMPORT_END


IMPORT_FUNC(VMCraftingModifyMovementSpeed, RETVAL_INT, CraftingModifyMovementSpeed)
	IMPORT_CONTEXT,  
	IMPORT_INT(nModAmount)
IMPORT_END

IMPORT_FUNC(VMRecipePropChance, RETVAL_INT, RecipePropChance)
	IMPORT_CONTEXT,  
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp),
	IMPORT_INT(nMinValue),
	IMPORT_INT(nMaxValue)
IMPORT_END

IMPORT_FUNC(VMRecipePropValue, RETVAL_INT, RecipePropValue)
	IMPORT_CONTEXT,  
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp),
	IMPORT_INT(nMinValue),
	IMPORT_INT(nMaxValue)
IMPORT_END

IMPORT_FUNC(VMCraftingAddPctChance, RETVAL_INT, CraftingAddPctChance)
	IMPORT_CONTEXT,  
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp),
	IMPORT_INT(nValue)
IMPORT_END

IMPORT_FUNC(VMCraftingSetPctChance, RETVAL_INT, CraftingSetPctChance)
	IMPORT_CONTEXT,  
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp),
	IMPORT_INT(nValue)
IMPORT_END

IMPORT_FUNC(VMCraftingSetPctOfValue, RETVAL_INT, CraftingSetPctOfValue)
	IMPORT_CONTEXT,  
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp),
	IMPORT_INT(nValue)
IMPORT_END

IMPORT_FUNC(VMCraftingSetValue, RETVAL_INT, CraftingSetValue)
	IMPORT_CONTEXT,  
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp),
	IMPORT_INT(nValue),
	IMPORT_INT(nPctOfValue)
IMPORT_END

IMPORT_FUNC(VMRecipe_UnitDataMinDmg, RETVAL_INT, Recipe_UnitDataMinDmg)
	IMPORT_CONTEXT,
	IMPORT_INT(nModValue)
IMPORT_END

IMPORT_FUNC(VMRecipe_UnitDataMaxDmg, RETVAL_INT, Recipe_UnitDataMaxDmg)
	IMPORT_CONTEXT,
	IMPORT_INT(nModValue)
IMPORT_END

IMPORT_FUNC(VMRecipe_UnitDataACMin, RETVAL_INT, Recipe_UnitDataACMin)
	IMPORT_CONTEXT,
	IMPORT_INT(nModValue)
IMPORT_END

IMPORT_FUNC(VMRecipe_UnitDataACMax, RETVAL_INT, Recipe_UnitDataACMax)
	IMPORT_CONTEXT,
	IMPORT_INT(nModValue)
IMPORT_END

IMPORT_FUNC(VMRecipe_UnitDataStat, RETVAL_INT, Recipe_UnitDataStat)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_STATS, nStat )
IMPORT_END

IMPORT_FUNC(VMCraftingSetStatByRecipeProp, RETVAL_INT, CraftingSetStatByRecipeProp)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp ),
	IMPORT_INDEX(DATATABLE_STATS, nStat ),
	IMPORT_INT( nParam )
IMPORT_END

IMPORT_FUNC(VMCraftingSetDmgEffectByRecipeProp, RETVAL_INT, CraftingSetDamageEffectByRecipeProp )
	IMPORT_CONTEXT,	
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp ),
	IMPORT_INDEX(DATATABLE_DAMAGE_EFFECTS, nDamageEffect ),	
	IMPORT_INT( nMinRange ),
	IMPORT_INT( nMaxRange ),
	IMPORT_INT( nDurationLenMS )
IMPORT_END

IMPORT_FUNC(VMCraftingSetDamageEffectParamByRecipeProp, RETVAL_INT, CraftingSetDamageEffectParamByRecipeProp )
	IMPORT_CONTEXT,	
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp ),
	IMPORT_INDEX(DATATABLE_DAMAGE_EFFECTS, nDamageEffect ),	
	IMPORT_INT( nParam ),
	IMPORT_INT( nMinRange ),
	IMPORT_INT( nMaxRange )
IMPORT_END

IMPORT_FUNC(VMCraftingSetStatByRangeAndCategoryLvl, RETVAL_INT, CraftingSetStatByRangeAndCatLvl)
	IMPORT_CONTEXT,	
	IMPORT_INDEX(DATATABLE_STATS, nStat ),
	IMPORT_INT( nParam ),
	IMPORT_INT( nMinRange ),
	IMPORT_INT( nMaxRange )
IMPORT_END

IMPORT_FUNC(VMCraftingGetValRangeByRecipePropPCT, RETVAL_INT, CraftingGetValRangeByRecipePropPCT)
	IMPORT_CONTEXT,	
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp ),
	IMPORT_INT( nMinRange ),
	IMPORT_INT( nMaxRange )
IMPORT_END


IMPORT_FUNC(VMCraftingSetStatByRangeAndRecipePropPCT, RETVAL_INT, CraftingSetStatByRangeAndRecipePropPCT)
	IMPORT_CONTEXT,	
	IMPORT_INDEX(DATATABLE_RECIPEPROPERTIES, nRecipeProp ),
	IMPORT_INDEX(DATATABLE_STATS, nStat ),
	IMPORT_INT( nParam ),
	IMPORT_INT( nMinRange ),
	IMPORT_INT( nMaxRange )
IMPORT_END