#ifndef _DEFINITION_HEADER_INCLUDED_
#define _DEFINITION_HEADER_INCLUDED_

#ifndef _DEFINITION_COMMON_H_
#include "definition_common.h"
#endif

//-------------------------------------------------------------------------------------------------
enum {
	DEFINITION_GROUP_APPEARANCE = DEFINITION_GROUP_START_GAME,
	DEFINITION_GROUP_SKILL_EVENTS,
	DEFINITION_GROUP_STATES,
	DEFINITION_GROUP_ROOM_LAYOUT,
	DEFINITION_GROUP_AI,
	DEFINITION_GROUP_PARTICLE,
	DEFINITION_GROUP_GAME_GLOBAL,
	DEFINITION_GROUP_ROOM_PATH_NODE,
	DEFINITION_GROUP_COLOR_SET,
	DEFINITION_GROUP_DEMO_LEVEL,
};

inline struct GAME_GLOBAL_DEFINITION * DefinitionGetGameGlobal()
{
	return (struct GAME_GLOBAL_DEFINITION *) DefinitionGetByName( DEFINITION_GROUP_GAME_GLOBAL, "GameDefault" );
}

#endif