#include "importdefines.h"
#include "QuestScriptsTB.h"
#include "crafting_scripts.h"
#include "LevelAreasAndMapScriptsTB.h"

#ifndef _EXCEL_H_
#include "excel.h"
#endif

IMPORT_FUNC(VMABS, RETVAL_INT, abs)
  IMPORT_INT(a)  
IMPORT_END

IMPORT_FUNC(VMMin, RETVAL_INT, min)
  IMPORT_INT(a),
  IMPORT_INT(b)
IMPORT_END

IMPORT_FUNC(VMMax, RETVAL_INT, max)
  IMPORT_INT(a),
  IMPORT_INT(b)
IMPORT_END

IMPORT_FUNC(VMPin, RETVAL_INT, pin)
  IMPORT_INT(value),
  IMPORT_INT(min),
  IMPORT_INT(max)
IMPORT_END

IMPORT_FUNC(VMPercent, RETVAL_INT, pct)
  IMPORT_INT(a),
  IMPORT_INT(b)
IMPORT_END

IMPORT_FUNC(VMPercentFloat, RETVAL_INT, pctFloat)
  IMPORT_INT(a),
  IMPORT_INT(b),
  IMPORT_INT(c)
IMPORT_END

IMPORT_FUNC(VMRand, RETVAL_INT, rand)
  IMPORT_GAME,
  IMPORT_INT(a),
  IMPORT_INT(b)
IMPORT_END

IMPORT_FUNC(VMRandByUnitId, RETVAL_INT, randByUnitId)
  IMPORT_CONTEXT,
  IMPORT_INT(a),
  IMPORT_INT(b)
IMPORT_END

IMPORT_FUNC(VMChance, RETVAL_INT, chance)
  IMPORT_GAME,
  IMPORT_INT(nChance),
  IMPORT_INT(nChanceOutOf)
IMPORT_END


IMPORT_FUNC(VMChanceByStateMod, RETVAL_INT, chanceByStateMod)
  IMPORT_CONTEXT,
  IMPORT_INT(nChance),
  IMPORT_INT(nChanceOutOf),  
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT(nModBy)
IMPORT_END


IMPORT_FUNC(VMRandSkillSeed, RETVAL_INT, randSkillSeed)
  IMPORT_CONTEXT,
  IMPORT_INT(a),
  IMPORT_INT(b)
IMPORT_END

IMPORT_FUNC(VMRoll, RETVAL_INT, roll)
  IMPORT_GAME,
  IMPORT_INT(a),
  IMPORT_INT(b)
IMPORT_END

IMPORT_FUNC(VMPercentOfHundred, RETVAL_INT, divMult)
  IMPORT_CONTEXT,
  IMPORT_INT(a),
  IMPORT_INT(b),
  IMPORT_INT(c)
IMPORT_END

IMPORT_FUNC(VMDistribute, RETVAL_INT, distribute)
  IMPORT_GAME,
  IMPORT_INT(numdie),
  IMPORT_INT(diesize),
  IMPORT_INT(start)
IMPORT_END


IMPORT_FUNC(VMRoundStat, RETVAL_INT, roundstat)
  IMPORT_GAME,
  IMPORT_INDEX(DATATABLE_STATS, stat),
  IMPORT_INT(value)
IMPORT_END

IMPORT_FUNC(VMGetEventIDByName, RETVAL_INT, getEventType)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNIT_EVENT_TYPES, nAffixID)
IMPORT_END

IMPORT_FUNC(VMGetAffixIDByName, RETVAL_INT, getAffixIDByName)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_AFFIXES, nAffixID)
IMPORT_END

IMPORT_FUNC(VMSkillGetLevel, RETVAL_INT, get_skill_level)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_INDEX(DATATABLE_SKILLS, nSkill)
IMPORT_END

IMPORT_FUNC(VMSkillGetLevel_Object, RETVAL_INT, get_skill_level_object)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_SKILLS, nSkill)
IMPORT_END

IMPORT_FUNC(VMPickSkill, RETVAL_INT, pickskill)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_CONTEXT_STATS(stats),
  IMPORT_INT(nSkillLevel)
IMPORT_END

IMPORT_FUNC(VMPickSkillByUnitType, RETVAL_INT, pickskillbyunittype)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_CONTEXT_STATS(stats),
	IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType),
	IMPORT_INT(nSkillLevel)
IMPORT_END
 
IMPORT_FUNC(VMRemoveOldestPetOfType, RETVAL_INT, removeoldestpetoftype)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType)
IMPORT_END

IMPORT_FUNC(VMKillOldestPetOfType, RETVAL_INT, killoldestpetoftype)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType)
IMPORT_END

IMPORT_FUNC(VMScaleUnitToInMS, RETVAL_INT, scaleUnitToInMS)
	IMPORT_CONTEXT,
	IMPORT_INT(nScale),
	IMPORT_INT(nTimeMS)
IMPORT_END


IMPORT_FUNC(VMPickSkillBySkillGroup, RETVAL_INT, pickskillbyskillgroup)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_CONTEXT_STATS(stats),
	IMPORT_INDEX(DATATABLE_SKILLGROUPS, nSkillGroup),
	IMPORT_INT(nSkillLevel)
IMPORT_END

IMPORT_FUNC(VMLearnSkill, RETVAL_INT, learnskill)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_INDEX(DATATABLE_SKILLS, skill)
IMPORT_END



IMPORT_FUNC(VMGetStatFromOwnerDivBySkillVar, RETVAL_INT, getStatOwnerDivBySkillVar )
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_STATS, stat),
  IMPORT_INT( nVar )
IMPORT_END

IMPORT_FUNC(VMGetStatFromOwnerDivBy, RETVAL_INT, getStatOwnerDivBy)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_INDEX(DATATABLE_STATS, stat),
  IMPORT_INT( nDivBy )
IMPORT_END

IMPORT_FUNC(VMSwitchUnitAndObject, RETVAL_INT, switchUnitAndObject )
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetAchievementCompleteCount, RETVAL_INT, getAchievementCompleteCount )
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_ACHIEVEMENTS, nAchievementID)
IMPORT_END




IMPORT_FUNC(VMGetVarRange, RETVAL_INT, getVarRange )
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetSkillVariable, RETVAL_INT, getVar )
  IMPORT_CONTEXT,
  IMPORT_INT( nVariable )
IMPORT_END

IMPORT_FUNC(VMGetAttackerSkillVarBySkill, RETVAL_INT, getAttackerSkillVarBySkill )
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_SKILLS, nSkill),
  IMPORT_INT( nVariable )
IMPORT_END

IMPORT_FUNC(VMGetSkillVariableFromSkill, RETVAL_INT, getVarFromSkill )
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_SKILLS, nSkill),
  IMPORT_INT( nVariable )
IMPORT_END

IMPORT_FUNC(VMGetSkillVariableFromSkillWithLvl, RETVAL_INT, getVarFromSkillWithLvl )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, nSkill),
	IMPORT_INT( nVariable ),
	IMPORT_INT( nLevel )
IMPORT_END

IMPORT_FUNC(VMGetSkillVariableFromSkillFromObject, RETVAL_INT, getVarFromSkillFromObject )
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_SKILLS, nSkill),
  IMPORT_INT( nVariable )
IMPORT_END

IMPORT_FUNC(VMHasStateObject, RETVAL_INT, hasStateObject)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState )
IMPORT_END

IMPORT_FUNC(VMHasState, RETVAL_INT, hasState)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState )
IMPORT_END

IMPORT_FUNC(VMClearStateObject, RETVAL_INT, clearStateObject)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState )
IMPORT_END

IMPORT_FUNC(VMClearState, RETVAL_INT, clearState)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState )
IMPORT_END

IMPORT_FUNC(VMClearStateClient, RETVAL_INT, clearStateClient)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState )
IMPORT_END

IMPORT_FUNC(VMIsDualWielding, RETVAL_INT, isDualWielding)
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetWieldingIsACount, RETVAL_INT, getWieldingIsACount)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, unittype)
IMPORT_END

IMPORT_FUNC(VMSetState, RETVAL_INT, setState)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState )
IMPORT_END

IMPORT_FUNC(VMSetStateObject, RETVAL_INT, setStateObject)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState )
IMPORT_END

IMPORT_FUNC(VMSetStateWithTime, RETVAL_INT, setStateWithTimeMS)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS )
IMPORT_END

IMPORT_FUNC(VMAddStateWithTime, RETVAL_INT, addStateWithTimeMS)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS )
IMPORT_END

IMPORT_FUNC(VMAddStateWithTimeClient, RETVAL_INT, addStateWithTimeMSClient)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS )
IMPORT_END


IMPORT_FUNC(VMSetStateWithTimeOnObject, RETVAL_INT, setStateWithTimeMSOnObject)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS )
IMPORT_END

IMPORT_FUNC(VMSetStateWithTimeScriptOnObject, RETVAL_INT, setStateWithTimeMSScriptOnObject)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS )
IMPORT_END

IMPORT_FUNC(VMBroadcastEquipEvent, RETVAL_INT, BroadcastEquipEvent )
  IMPORT_CONTEXT
IMPORT_END


IMPORT_FUNC(VMSetAITargetToSkillTarget, RETVAL_INT, setAITargetToSkillTarget )
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMSetObjectAITargetToUnitAITarget, RETVAL_INT, setObjectAITargetToUnitAITarget )
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMMakeAIAwareOfObject, RETVAL_INT, makeAIAwareOfObject )
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMSetAITargetToObject, RETVAL_INT, setAITargetToObject )
  IMPORT_CONTEXT
IMPORT_END


IMPORT_FUNC(VMGetPossibleTargetCount, RETVAL_INT, getPossibleTargetCount )
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMHasSkillTarget, RETVAL_INT, hasSkillTarget )
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMSetStateOnSkillTargetWithTimeMSScript, RETVAL_INT, setStateOnSkillTargetWithTimeMSScript)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS ),
  IMPORT_INT( clearFirst )
IMPORT_END

IMPORT_FUNC(VMRunScriptParamOnStateClear, RETVAL_INT, runScriptParamOnStateClear)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( paramIndex )
IMPORT_END

IMPORT_FUNC(VMGetCountOfUnitTypeInArea, RETVAL_INT, getCountOfUnitsInArea )
  IMPORT_CONTEXT,    
  IMPORT_INT( area )  
IMPORT_END


IMPORT_FUNC(VMRunScriptOnUnitsInAreaPCT, RETVAL_INT, runScriptOnUnitsInAreaPCT )
  IMPORT_CONTEXT,  
  IMPORT_INT( scriptIndex ),
  IMPORT_INT( area ),
  IMPORT_INT( chance ),
  IMPORT_INT( flag )  
IMPORT_END

IMPORT_FUNC(VMDoSkillAndScriptOnUnitsInAreaPCT, RETVAL_INT, doSkillAndScriptOnUnitsInAreaPCT )
  IMPORT_CONTEXT,  
  IMPORT_INDEX( DATATABLE_SKILLS, nSkill ),
  IMPORT_INT( scriptIndex ),
  IMPORT_INT( area ),
  IMPORT_INT( chance ),
  IMPORT_INT( flag )  
IMPORT_END

IMPORT_FUNC(VMDoSkillOnUnitsInAreaPCT, RETVAL_INT, doSkillOnUnitsInAreaPCT )
  IMPORT_CONTEXT,  
  IMPORT_INDEX( DATATABLE_SKILLS, nSkill ),
  IMPORT_INT( area ),
  IMPORT_INT( chance ),
  IMPORT_INT( flag )  
IMPORT_END

IMPORT_FUNC(VMSetStateWithTimeAndScript, RETVAL_INT, setStateWithTimeMSScript)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS )
IMPORT_END

IMPORT_FUNC(VMSetStateWithTimeAndScriptParam, RETVAL_INT, setStateWithTimeMSScriptParam)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS ),
  IMPORT_INT( paramIndex )
IMPORT_END

IMPORT_FUNC(VMSetStateWithTimeAndScriptParamObject, RETVAL_INT, setStateWithTimeMSScriptParamObject)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS ),
  IMPORT_INT( paramIndex )
IMPORT_END


IMPORT_FUNC(VMAddStateWithTimeAndScriptParamObject, RETVAL_INT, addStateWithTimeMSScriptParamObject)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS ),
  IMPORT_INT( paramIndex )
IMPORT_END

IMPORT_FUNC(VMAddStateWithTimeAndScript, RETVAL_INT, addStateWithTimeMSScript)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS )
IMPORT_END


IMPORT_FUNC(VMAddStateWithTimeAndScriptParam, RETVAL_INT, addStateWithTimeMSScriptParam)
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATES, nState ),
  IMPORT_INT( timerMS ),
  IMPORT_INT( paramIndex )
IMPORT_END

IMPORT_FUNC(VMSetEffect, RETVAL_INT, setDmgEffect )
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_DAMAGE_EFFECTS, nDmgEffect ),
  IMPORT_INT( nChance ),
  IMPORT_INT( nTime ),
  IMPORT_INT( nRoll )
IMPORT_END

IMPORT_FUNC(VMGetStatFromOwner, RETVAL_INT, getStatOwner)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMGetStatParent, RETVAL_INT, getStatParent)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMAddPCTStatOnOwner, RETVAL_INT, addPCTStatOnOwner )
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATS, nStat ),
  IMPORT_INT( nValue ),
  IMPORT_INT( nParam )
IMPORT_END

IMPORT_FUNC(VMSetStatOnOwner, RETVAL_INT, setStatOnOwner )
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_STATS, nStat ),
  IMPORT_INT( nValue ),
  IMPORT_INT( nParam )
IMPORT_END

IMPORT_FUNC(VMGetStatTotal, RETVAL_INT, total)
  IMPORT_VMSTATE,
  IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMGetBaseStatTotal, RETVAL_INT, basetotal)
  IMPORT_VMSTATE,
  IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMGetBaseStat, RETVAL_INT, basestat)
  IMPORT_VMSTATE,
  IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMGetStatCur, RETVAL_INT, getcur)
  IMPORT_VMSTATE,
  IMPORT_INDEX(DATATABLE_STATS, stat),
  IMPORT_STAT_PARAM(param)
IMPORT_END

IMPORT_FUNC(VMGetStatIndex, RETVAL_INT, statidx)
  IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMGetInvLocCount, RETVAL_INT, invcount)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_INDEX(DATATABLE_INVLOCIDX, location)
IMPORT_END

IMPORT_FUNC(VMItemIsInInvLoc, RETVAL_INT, is_in_invloc)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_INVLOCIDX, location)
IMPORT_END

IMPORT_FUNC(VMDamageRider, RETVAL_INT, dmgrider)
  IMPORT_VMSTATE
IMPORT_END

IMPORT_FUNC(VMProcRider, RETVAL_INT, procrider)
  IMPORT_VMSTATE
IMPORT_END

IMPORT_FUNC(VMKnockback, RETVAL_INT, knockback)
  IMPORT_CONTEXT,
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMColorCodeRequirement, RETVAL_INT, colorcoderequirement)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_STATS, stat),
	IMPORT_STAT_PARAM(param)
IMPORT_END

IMPORT_FUNC(VMColorCodeModUnitRequirement, RETVAL_INT, color_code_modunit_requirement)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_STATS, stat),
	IMPORT_STAT_PARAM(param)
IMPORT_END

IMPORT_FUNC(VMColorCodeModUnitRequirement2, RETVAL_INT, color_code_modunit_requirement2)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_STATS, stat1),
	IMPORT_STAT_PARAM(param1),
	IMPORT_INDEX(DATATABLE_STATS, stat2),
	IMPORT_STAT_PARAM(param2)
IMPORT_END

IMPORT_FUNC(VMFeedChangeForHoverItem, RETVAL_INT, feedchange)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_STATS, stat),
	IMPORT_INT(nCheckBonus)
IMPORT_END

IMPORT_FUNC(VMStatChangeForHoverItem, RETVAL_INT, hoverstatchange)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMFeedColorCode, RETVAL_INT, feedcolorcode)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_STATS, stat)
IMPORT_END

IMPORT_FUNC(VMColorCodePosNegVal2, RETVAL_INT, color_code_pos_neg_val2)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodePosNeg, RETVAL_INT, colorposneg)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodePrice, RETVAL_INT, colorcodeprice)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMColorCodeClassRequirement, RETVAL_INT, colorcodeclassreq)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeSkillSlots, RETVAL_INT, colorcodeskillslots)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeSkillUsability, RETVAL_INT, colorcodeskillusable)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeSkillGroupUsability, RETVAL_INT, colorcodeskillgroupusable)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMItemMeetsClassReqs, RETVAL_INT, meetsclassreqs)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMFontColor, RETVAL_INT, fontcolorrow)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_FONTCOLORS, nColorIndex)
IMPORT_END

IMPORT_FUNC(VMItemIsNoDrop, RETVAL_INT, nodrop)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemIsNoTrade, RETVAL_INT, notrade)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMObjectIsNoTrade, RETVAL_INT, objectNotrade)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMItemBuyPriceByValue, RETVAL_INT, BuyPriceByValue)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(valueType)
IMPORT_END

IMPORT_FUNC(VMItemSellPriceByValue, RETVAL_INT, SellPriceByValue)
IMPORT_CONTEXT_UNIT(unit),
IMPORT_INT(valueType)
IMPORT_END

IMPORT_FUNC(VMItemBuyPrice, RETVAL_INT, buyprice)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMBuyPriceRealWorld, RETVAL_INT, buypriceRealWorld)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemSellPrice, RETVAL_INT, sellprice)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END
IMPORT_FUNC(VMItemSellPriceRealWorld, RETVAL_INT, sellpriceRealWorld)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END


IMPORT_FUNC(VMHitChance, RETVAL_INT, hitChance)
IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMDodgeChance, RETVAL_INT, dodgeChance)
IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemNumAffixes, RETVAL_INT, numaffixes)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemQualityPriceMult, RETVAL_INT, qualitypricemult)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMEnemiesInRadius, RETVAL_INT, enemies_in_radius)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMVisibleEnemiesInRadius, RETVAL_INT, visible_enemies_in_radius)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMChampionsInRadius, RETVAL_INT, champions_in_radius)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMDistanceSquaredToChampion, RETVAL_INT, distance_sq_to_champion)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMChampionHPPct, RETVAL_INT, champion_hp_pct)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMBossesInRadius, RETVAL_INT, bosses_in_radius)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMDistanceSquaredToBoss, RETVAL_INT, distance_sq_to_boss)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMBossHPPct, RETVAL_INT, boss_hp_pct)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMEnemyCorpsesInRadius, RETVAL_INT, enemy_corpses_in_radius)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(radius)
IMPORT_END

IMPORT_FUNC(VMMonstersKilled, RETVAL_INT, monsters_killed)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(time)
IMPORT_END

IMPORT_FUNC(VMMonstersKilledNonTeam, RETVAL_INT, monsters_killed_nonteam)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(time)
IMPORT_END

IMPORT_FUNC(VMMonstersPctLeft, RETVAL_INT, monsters_pct_left)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMHPLost, RETVAL_INT, hp_lost)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(time)
IMPORT_END

IMPORT_FUNC(VMMetersMoved, RETVAL_INT, meters_moved)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(time)
IMPORT_END

IMPORT_FUNC(VMAttacks, RETVAL_INT, attacks)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(time)
IMPORT_END

IMPORT_FUNC(VMIsAlive, RETVAL_INT, is_alive)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMMonsterLevel, RETVAL_INT, monster_level)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMHasActiveTask, RETVAL_INT, has_active_task)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMIsUsable, RETVAL_INT, is_usable)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMIsExaminable, RETVAL_INT, is_examinable)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMIsOperatable, RETVAL_INT, is_operatable)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMUnitContainsUnitType, RETVAL_INT, UnitContainsUnitType)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_UNITTYPES, unittype)
IMPORT_END



IMPORT_FUNC(VMIsA, RETVAL_INT, isa)
  IMPORT_CONTEXT_UNIT(unit),
  IMPORT_INDEX(DATATABLE_UNITTYPES, unittype)
IMPORT_END

IMPORT_FUNC(VMIsSubscriber, RETVAL_INT, is_subscriber)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMIsHardcore, RETVAL_INT, is_hardcore)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMIsElite, RETVAL_INT, is_elite)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMGetDifficulty, RETVAL_INT, get_difficulty)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMSameGameVariant, RETVAL_INT, same_game_variant)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMPlayerIsInGuild, RETVAL_INT, player_is_in_guild)
	IMPORT_CONTEXT
IMPORT_END


IMPORT_FUNC(VMGetTierInvestmentForPane, RETVAL_INT, getTierInvestmentForPane)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLTABS, nPaneIndex)
IMPORT_END

IMPORT_FUNC(VMGetStat, RETVAL_INT, GetStat)
IMPORT_CONTEXT_UNIT(unit),
IMPORT_INDEX(DATATABLE_STATS, stat),
IMPORT_STAT_PARAM(param)
IMPORT_END

IMPORT_FUNC(VMGetAct, RETVAL_INT, get_act)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMEmailSendItemOkay, RETVAL_INT, email_send_item_okay)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMEmailReceiveItemOkay, RETVAL_INT, email_receive_item_okay)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeSubscriber, RETVAL_INT, colorcodesubscriber)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMItemRequiresSubscriber, RETVAL_INT, item_requires_subscriber)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMColorCodeVariantNormal, RETVAL_INT, colorcodevariantnormal)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeVariantHardcore, RETVAL_INT, colorcodevarianthardcore)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeVariantElite, RETVAL_INT, colorcodevariantelite)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeVariantHardcoreElite, RETVAL_INT, colorcodevarianthardcoreelite)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMColorCodeNightmare, RETVAL_INT, colorcodenightmare)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMItemIsNightmareSpecific, RETVAL_INT, item_is_nightmare_specific)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemIsVariantNormal, RETVAL_INT, item_is_variant_normal)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemIsVariantHardcore, RETVAL_INT, item_is_variant_hardcore)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemIsVariantElite, RETVAL_INT, item_is_variant_elite)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemIsVariantHardcoreElite, RETVAL_INT, item_is_variant_hardcore_elite)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMItemQuality, RETVAL_INT, quality)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMMeetsItemRequirements, RETVAL_INT, meetsitemreqs)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMWeaponDPS, RETVAL_INT, weapondps)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMSkillTargetIsA, RETVAL_INT, SkillTargetIsA)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, unittype)
IMPORT_END

IMPORT_FUNC(VMGetStatFromExecutedUnit, RETVAL_INT, getStatFromExecutedUnit)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_STATS, unittype)
IMPORT_END

IMPORT_FUNC(VMItemSkillScript, RETVAL_INT, parseExecutedItemSkillScript)
	IMPORT_CONTEXT,
	IMPORT_INT( nScriptIndex )
IMPORT_END

IMPORT_FUNC(VMGetObjectClassID, RETVAL_INT, getObjectClassID)
	IMPORT_CONTEXT
IMPORT_END


IMPORT_FUNC(VMCopyExecutedUnitProps, RETVAL_INT, copyExecutedUnitProps)
	IMPORT_CONTEXT,
	IMPORT_INT( nPropIndex )
IMPORT_END

IMPORT_FUNC(VMGetItemCoolDown, RETVAL_INT, getItemCoolDown)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetItemDuration, RETVAL_INT, getItemDuration)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetItemDurationMS, RETVAL_INT, getItemDurationMS)
	IMPORT_CONTEXT
IMPORT_END


IMPORT_FUNC(VMGetObjectIsA, RETVAL_INT, GetObjectIsA)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, unittype)
IMPORT_END

IMPORT_FUNC(VMGetMissileSourceIsA, RETVAL_INT, GetMissileSourceIsA)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, unittype)
IMPORT_END




IMPORT_FUNC(VMSkillHasReqWeapon, RETVAL_INT, GetSkillHasReqWeapon )
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMItemHasSkillWhenUsed, RETVAL_INT, has_use_skill )
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMHasDomName, RETVAL_INT, hasdomname)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMDamageDone, RETVAL_INT, dps)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(time)
IMPORT_END

IMPORT_FUNC(VMObjectCanUpgrade, RETVAL_INT, ObjectCanUpgrade)
	IMPORT_CONTEXT
IMPORT_END


IMPORT_FUNC(VMUseStateDuration, RETVAL_INT, use_state_duration)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMUsesMissiles, RETVAL_INT, uses_missiles)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMUsesLasers, RETVAL_INT, uses_lasers)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMHasDamageRadius, RETVAL_INT, has_damage_radius)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMGetMissileCount, RETVAL_INT, missile_count)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMGetLaserCount, RETVAL_INT, laser_count)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMGetShotsPerMinute, RETVAL_INT, shots_per_minute)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMGetMillisecondsPerShot, RETVAL_INT, milliseconds_per_shot)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMGetPlayerCritChance, RETVAL_INT, player_crit_chance)
	IMPORT_CONTEXT_UNIT(pUnit),
	IMPORT_INT(nSlot)
IMPORT_END

IMPORT_FUNC(VMGetPlayerCritDamage, RETVAL_INT, player_crit_damage)
	IMPORT_CONTEXT_UNIT(pUnit),
	IMPORT_INT(nSlot)
IMPORT_END

IMPORT_FUNC(VMAddItemLevelArmor, RETVAL_INT, add_item_level_armor)
	IMPORT_CONTEXT,
	IMPORT_INT(nLevel),
	IMPORT_INT(nPercent)
IMPORT_END

IMPORT_FUNC(VMGetPlayerLevelSkillPowerCostPercent, RETVAL_INT, player_level_skill_power_cost_percent)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetItemLevelDamageMult, RETVAL_INT, item_level_damage_mult)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetItemLevelFeed, RETVAL_INT, item_level_feed)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetItemLevelSfxAttack, RETVAL_INT, item_level_sfx_attack)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetItemLevelSfxDefense, RETVAL_INT, item_level_sfx_defense)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetItemLevelShieldBuffer, RETVAL_INT, item_level_shield_buffer)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetMonsterLevelSfxDefense, RETVAL_INT, monster_level_sfx_defense)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetMonsterLevelSfxAttack, RETVAL_INT, monster_level_sfx_attack)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetMonsterLevelDamage, RETVAL_INT, monster_level_damage)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetMonsterLevelDamagePCT, RETVAL_INT, monster_level_damage_pct)
	IMPORT_INT(nLevel),
	IMPORT_INT(nPCT)
IMPORT_END

IMPORT_FUNC(VMGetMonsterLevelShields, RETVAL_INT, monster_level_shields)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetMonsterLevelArmor, RETVAL_INT, monster_level_armor)
	IMPORT_INT(level)
IMPORT_END

IMPORT_FUNC(VMGetUnitLevelAIChangerAttack, RETVAL_INT, unit_ai_changer_attack)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMDoesFieldDamage, RETVAL_INT, does_field_damage)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMDistToPlayer, RETVAL_INT, distance_to_player)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMHasContainer, RETVAL_INT, has_container)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMMonsterArmor, RETVAL_INT, monster_armor)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_DAMAGETYPES, nDamageType),
	IMPORT_INT(nPercent)
IMPORT_END


IMPORT_FUNC(VMGetProcID, RETVAL_INT, getProcID )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_PROCS, nProc)
IMPORT_END

IMPORT_FUNC(VMGetDamageEffectID, RETVAL_INT, getDamageEffectID )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_DAMAGE_EFFECTS, nDamageEffect)
IMPORT_END

IMPORT_FUNC(VMGetDmgType, RETVAL_INT, getDmgType )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_DAMAGETYPES, nDamageType)
IMPORT_END

IMPORT_FUNC(VMGetUnitTypeID, RETVAL_INT, getUnitTypeID )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType)
IMPORT_END

IMPORT_FUNC(VMGetSkillDmgMult, RETVAL_INT, getSkillDmgMult)
  IMPORT_CONTEXT,
  IMPORT_INT(nSkillLvl),
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMGetArmorDmgMult, RETVAL_INT, getSkillArmorMult)
  IMPORT_CONTEXT,
  IMPORT_INT(nSkillLvl),
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMGetAttackSpeedDmgMult, RETVAL_INT, getSkillAttackSpeedMult)
  IMPORT_CONTEXT,
  IMPORT_INT(nSkillLvl),
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMGetToHitMult, RETVAL_INT, getSkillToHitMult)
  IMPORT_CONTEXT,
  IMPORT_INT(nSkillLvl),
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMGetPctDmgMult, RETVAL_INT, getSkillPctDmgMult)
  IMPORT_CONTEXT,
  IMPORT_INT(nSkillLvl),
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMGetPetCountOfType, RETVAL_INT, getPetCountOfType )
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType)
IMPORT_END

IMPORT_FUNC(VMRunScriptParamOnPetsOfType, RETVAL_INT, runScriptOnPetsOfType )
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType),
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMApplyRandomAffixOfType, RETVAL_INT, randaffixtype)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_AFFIXTYPES, affixType)
IMPORT_END

IMPORT_FUNC(VMApplyRandomAffixOfGroup, RETVAL_INT, randaffixgroup)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_AFFIX_GROUPS, affixGroup)
IMPORT_END

IMPORT_FUNC(VMApplyAffix, RETVAL_INT, applyaffix)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_AFFIXES, affix),
  IMPORT_INT(bForce)
IMPORT_END

IMPORT_FUNC(VMGetBonusValue, RETVAL_INT, getBonusValue )
  IMPORT_CONTEXT,  
  IMPORT_INT(a)
IMPORT_END

IMPORT_FUNC(VMGetBonusAll, RETVAL_INT, getBonusAll )
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetDMGAugmentation, RETVAL_INT, getDMGAugmentation)
  IMPORT_CONTEXT,  
  IMPORT_INT(nSkillVar),
  IMPORT_INT(nLevel),
  IMPORT_INT(nPercentOfLevel ),
  IMPORT_INT(nSkillPointsInvested)  
IMPORT_END

IMPORT_FUNC(VMGetDMGAugmentationPCT, RETVAL_INT, getDMGAugmentationPCT)
  IMPORT_CONTEXT,  
  IMPORT_INT(nSkillVar),
  IMPORT_INT(nLevel),
  IMPORT_INT(nPercentOfLevel ),
  IMPORT_INT(nSkillPointsInvested)  
IMPORT_END

IMPORT_FUNC(VMGetMonsterHPAtLevel, RETVAL_INT, getMonsterHPAtLevel)
  IMPORT_CONTEXT,  
  IMPORT_INT(nLevel)
IMPORT_END

IMPORT_FUNC(VMGetMonsterHPAtLevelPCT, RETVAL_INT, getMonsterHPAtLevelByPCT)
  IMPORT_CONTEXT,  
  IMPORT_INT(nLevel),
  IMPORT_INT(nPCT)
IMPORT_END


IMPORT_FUNC(VMDisplayDamageAbsorbed, RETVAL_INT, display_dmg_absorbed_pct)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMDamagePctByEnergy, RETVAL_INT, dmg_percent_by_energy)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMWeaponGetRange, RETVAL_INT, weapon_range)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMObjectIsDestructable, RETVAL_INT, IsObjectDestructable )
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGlobalThemeIsEnabled, RETVAL_INT, GlobalThemeIsEnabled )
	IMPORT_CONTEXT,  
	IMPORT_INDEX(DATATABLE_GLOBAL_THEMES, nTheme)
IMPORT_END



IMPORT_FUNC(VMRemoveHPAndCheckForDeath, RETVAL_INT, RemoveHPAndCheckForDeath )
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT(nRemove)
IMPORT_END

IMPORT_FUNC(VMGetSkillStat, RETVAL_INT, getSkillStat)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_SKILL_STATS, nSkillStat),
  IMPORT_INT( nSkillLvl )
IMPORT_END

IMPORT_FUNC(VMGetItemStatByPct, RETVAL_INT, getItemStatByPct)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILL_STATS, nSkillStat),
	IMPORT_INT( nPct )
IMPORT_END




IMPORT_FUNC(VMTownPortalIsAllowed, RETVAL_INT, TownPortalIsAllowed)
	IMPORT_CONTEXT_UNIT(unit)	
IMPORT_END

IMPORT_FUNC(VMLowerManaCostOnSkillPct, RETVAL_INT, lowerManaCostOnSkillByPct )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID ),
	IMPORT_INT(nPctPower)
IMPORT_END

IMPORT_FUNC(VMLowerCoolDownOnSkillPct, RETVAL_INT, lowerCoolDownOnSkillByPct )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID ),
	IMPORT_INT(nPctCooldown)
IMPORT_END


IMPORT_FUNC(VMSkillIsOn, RETVAL_INT, skillIsOn )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMGetSkillRange, RETVAL_INT, getSkillRange )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END


IMPORT_FUNC(VMSetEffectParams, RETVAL_INT, setDmgEffectParams )
  IMPORT_CONTEXT,
  IMPORT_INDEX( DATATABLE_DAMAGE_EFFECTS, nDmgEffect ),
  IMPORT_INT( nParam0 ),
  IMPORT_INT( nParam1 ),
  IMPORT_INT( nParam2 )
IMPORT_END

IMPORT_FUNC(VMSetDamageEffectSkill, RETVAL_INT, setDmgEffectSkill )
	IMPORT_CONTEXT,
	IMPORT_INDEX( DATATABLE_DAMAGE_EFFECTS, nDmgEffect ),
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMSetDamageEffectSkillOnTarget, RETVAL_INT, setDmgEffectSkillOnTarget )
	IMPORT_CONTEXT,
	IMPORT_INDEX( DATATABLE_DAMAGE_EFFECTS, nDmgEffect ),
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMGetSkillID, RETVAL_INT, getSkillID )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMFireMissileFromObject, RETVAL_INT, fireMissileFromObject )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_MISSILES, missileID )
IMPORT_END

IMPORT_FUNC(VMCaculateGemSockets, RETVAL_INT, caculateGemSockets )
	IMPORT_CONTEXT	
IMPORT_END

IMPORT_FUNC(VMCaculateRareGemSockets, RETVAL_INT, caculateRareGemSockets )
	IMPORT_CONTEXT	
IMPORT_END

IMPORT_FUNC(VMExecuteSkill, RETVAL_INT, executeSkill )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMExecuteSkillOnObject, RETVAL_INT, executeSkillOnObject )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMStopSkill, RETVAL_INT, stopSkill )
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMSkillPowerCost, RETVAL_INT, powercost )
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_SKILLS, skillID )
IMPORT_END

IMPORT_FUNC(VMSkillPowerCostAtLevel, RETVAL_INT, powercost_at_level )
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_SKILLS, skillID ),
	IMPORT_INT( nSkillLevel )
IMPORT_END

IMPORT_FUNC(VMIsStashUIOpen, RETVAL_INT, is_stash_ui_open )
IMPORT_END

IMPORT_FUNC(VMSetRecipeLearned, RETVAL_INT, setRecipeLearned)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetRecipeLearned, RETVAL_INT, getRecipeLearned)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetRecipeCategoryLevel, RETVAL_INT, getRecipeCategoryLevel)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_RECIPECATEGORIES, nCategory )
IMPORT_END

IMPORT_FUNC(VMCreateRecipe, RETVAL_INT, createRecipe)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMCreateSpecificRecipe, RETVAL_INT, createSpecificRecipe)
  IMPORT_CONTEXT,
  IMPORT_INDEX(DATATABLE_RECIPES, nRecipeID)
IMPORT_END

IMPORT_FUNC(VMGetCurrentGameTick, RETVAL_INT, getCurrentGameTick )
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetSkillMaxLevel, RETVAL_INT, getSkillMaxLevel )
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGiveAllRecipes, RETVAL_INT, giveAllRecipes )
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMGetSkillPctInvested, RETVAL_INT, getSkillPctInvested )
	IMPORT_CONTEXT,
	IMPORT_INT( nSkillLevel )
IMPORT_END

IMPORT_FUNC(VMHasA, RETVAL_INT, has_a)
	IMPORT_CONTEXT,
	IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType)
IMPORT_END

IMPORT_FUNC(VMAddToAnchorMakers, RETVAL_INT, AddToAnchorMakers)
IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMItemBelongsToGambler, RETVAL_INT, item_belongs_to_gambler)
	IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMReevaluateDefense, RETVAL_INT, reevaluate_defense)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMPlayerLevelAttackRating, RETVAL_INT, player_level_attack_rating)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMPetLevelAttackRating, RETVAL_INT, pet_level_attack_rating)
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INT( nLevel )
IMPORT_END

IMPORT_FUNC(VMPetReevaluateDefense, RETVAL_INT, pet_reevaluate_defense)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMReevaluateFeed, RETVAL_INT, reevaluate_feed)
	IMPORT_CONTEXT_UNIT(unit)
IMPORT_END

IMPORT_FUNC(VMStatGetShift, RETVAL_INT, shift )
	IMPORT_GAME,
	IMPORT_INDEX(DATATABLE_STATS, stat )
IMPORT_END

IMPORT_FUNC(VMCombatHasSecondaryAttacks, RETVAL_INT, combat_has_secondary_attacks)
	IMPORT_GAME
IMPORT_END

IMPORT_FUNC(VMCombatIsPrimaryAttack, RETVAL_INT, combat_is_primary_attack)
	IMPORT_GAME
IMPORT_END

IMPORT_FUNC(VMGetSkillScriptParam, RETVAL_INT, skill_script_param)
	IMPORT_GAME,
	IMPORT_CONTEXT_UNIT(unit),
	IMPORT_INDEX(DATATABLE_STATES, state )
IMPORT_END
