#include "importdefines.h"


IMPORT_FUNC(VMSetUnitTypeVisAreaFloor, RETVAL_INT, setUnitTypeAreaFloorVis)
  IMPORT_CONTEXT,  
  /*IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType),  */
  IMPORT_INDEX(DATATABLE_LEVEL_AREAS, nLevelArea),
  IMPORT_INT(nFloor),
  IMPORT_INT(nVis)
IMPORT_END

IMPORT_FUNC(VMSetUnitTypeAreaFloorInteractive, RETVAL_INT, setUnitTypeAreaFloorInteractive)
  IMPORT_CONTEXT,  
  /*IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType),  */
  IMPORT_INDEX(DATATABLE_LEVEL_AREAS, nLevelArea),
  IMPORT_INT(nFloor)
IMPORT_END

IMPORT_FUNC(VMSetUnitTypeAreaFloorDisabled, RETVAL_INT, setUnitTypeAreaFloorDisabled)
  IMPORT_CONTEXT,  
  /*IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType),  */
  IMPORT_INDEX(DATATABLE_LEVEL_AREAS, nLevelArea),
  IMPORT_INT(nFloor)
IMPORT_END

IMPORT_FUNC(VMShowQuestItemDialog, RETVAL_INT, showQuestItemDialog)
  IMPORT_CONTEXT
IMPORT_END

IMPORT_FUNC(VMSetQuestBit, RETVAL_INT, setQuestBit)
  IMPORT_CONTEXT,    
  IMPORT_INT(nBit)
IMPORT_END

IMPORT_FUNC(VMGetQuestBit, RETVAL_INT, getQuestBit)
  IMPORT_CONTEXT,    
  IMPORT_INT(nBit)
IMPORT_END

IMPORT_FUNC(VMIsQuestTaskComplete, RETVAL_INT, isQuestTaskComplete)
  IMPORT_CONTEXT,    
  IMPORT_INDEX(DATATABLE_QUESTS_TASKS_FOR_TUGBOAT, nQuestTask)
IMPORT_END

IMPORT_FUNC(VMIsQuestTaskActive, RETVAL_INT, isQuestTaskActive)
  IMPORT_CONTEXT,    
  IMPORT_INDEX(DATATABLE_QUESTS_TASKS_FOR_TUGBOAT, nQuestTask)
IMPORT_END

IMPORT_FUNC(VMIsTalkingTo, RETVAL_INT, isTalkingTo)
  IMPORT_CONTEXT,  
  IMPORT_INDEX(DATATABLE_NPC, nNPCID)
IMPORT_END

IMPORT_FUNC(VMSetTargetVisibility, RETVAL_INT, setTargetVisibility)
  IMPORT_CONTEXT,  
  IMPORT_INT(nVis)
IMPORT_END

IMPORT_FUNC(VMSetTargetVisibilityOnFloor, RETVAL_INT, setTargetVisibilityOnFloor)
  IMPORT_CONTEXT,  
  IMPORT_INT(nVis),
  IMPORT_INT(nFloor)
IMPORT_END

IMPORT_FUNC(VMSetStateOnTarget, RETVAL_INT, setStateOnTarget)
  IMPORT_CONTEXT,  
  IMPORT_INDEX(DATATABLE_STATES, nState)
IMPORT_END

IMPORT_FUNC(VMSetTargetInteractive, RETVAL_INT, setTargetInteractive)
  IMPORT_CONTEXT,  
  IMPORT_INT(nInteractive)
IMPORT_END

IMPORT_FUNC(VMSetTargetTeam, RETVAL_INT, setTargetToTeam)
  IMPORT_CONTEXT,  
  IMPORT_INT(nTeam)
IMPORT_END

IMPORT_FUNC(VMGetIsTargetOfType, RETVAL_INT, getIsTargetOfType)
  IMPORT_CONTEXT,  
  IMPORT_INDEX(DATATABLE_UNITTYPES, nUnitType)
IMPORT_END

IMPORT_FUNC(VMSetMonsterInLevelToTarget, RETVAL_INT, setMonsterInLevelToTarget)
  IMPORT_CONTEXT,  
  IMPORT_INDEX(DATATABLE_MONSTERS, nMonsterID)
IMPORT_END

IMPORT_FUNC(VMSetObjectInLevelToTarget, RETVAL_INT, setObjectInLevelToTarget)
  IMPORT_CONTEXT,  
  IMPORT_INDEX(DATATABLE_OBJECTS, nObjectID)
IMPORT_END

IMPORT_FUNC(VMGetIsTargetMonster, RETVAL_INT, getIsTargetMonster)
  IMPORT_CONTEXT,  
  IMPORT_INDEX(DATATABLE_MONSTERS, nMonsterID)
IMPORT_END

IMPORT_FUNC(VMGetIsTargetObject, RETVAL_INT, getIsTargetObject)
  IMPORT_CONTEXT,  
  IMPORT_INDEX(DATATABLE_OBJECTS, nObjectID)
IMPORT_END

IMPORT_FUNC(VMResetTargetObject, RETVAL_INT, resetTargetObject)
  IMPORT_CONTEXT  
IMPORT_END

IMPORT_FUNC(VMMessageStatVal, RETVAL_INT, messageStatVal)
  IMPORT_CONTEXT,    
  IMPORT_INDEX(DATATABLE_STATS, nStatId),
  IMPORT_INT(nIndex)
IMPORT_END

IMPORT_FUNC(VMGetStatVal, RETVAL_INT, getStatVal)
  IMPORT_CONTEXT,    
  IMPORT_INDEX(DATATABLE_STATS, nStatId),
  IMPORT_INT(nIndex)
IMPORT_END

