//----------------------------------------------------------------------------
// unittypes.h
//
// (C)Copyright 2003, Flagship Studios. All rights reserved.
//----------------------------------------------------------------------------
#ifndef _UNITTYPES_H_
#define _UNITTYPES_H_


//----------------------------------------------------------------------------
// DEFINES
//----------------------------------------------------------------------------
#ifndef _EXCEL_H_
#include "excel.h"
#endif


//----------------------------------------------------------------------------
// DEFINES
//----------------------------------------------------------------------------
enum
{
	MAX_UNITTYPE_EQUIV = 16,
};


//----------------------------------------------------------------------------
// ENUMERATIONS
//----------------------------------------------------------------------------
#include "..\data_common\excel\unittypes_hdr.h"	// auto-generated by unittypes.xls


//----------------------------------------------------------------------------
// STRUCTS
//----------------------------------------------------------------------------
struct UNITTYPE_DATA
{
	char			szName[DEFAULT_INDEX_SIZE];
	WORD			wCode;
	int				nTypeEquiv[MAX_UNITTYPE_EQUIV];
	int				nDisplayName;
	int				nHellgateAuctionFaction;
	int				nHellgateAuctionType;
	int				nHellgateAuctionName;
	int				nMythosAuctionFaction;
	int				nMythosAuctionType;
	int				nMythosAuctionName;
};


//----------------------------------------------------------------------------
// FUNCTIONS
//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
inline const UNITTYPE_DATA * UnitTypeGetData(
	int nUnitType)
{
	return (const UNITTYPE_DATA *)ExcelGetData(EXCEL_CONTEXT(NULL), DATATABLE_UNITTYPES, nUnitType);
}	

//----------------------------------------------------------------------------
inline UINT32 UnitTypeGetCount()
{
	return ExcelGetCount(EXCEL_CONTEXT(NULL), DATATABLE_UNITTYPES);
}

//----------------------------------------------------------------------------
inline BOOL UnitIsA(
	int a,
	int b)
{
	if (a < 0 || b < 0)
	{
		return TRUE;
	}
	return ExcelTestIsA(EXCEL_CONTEXT(NULL), DATATABLE_UNITTYPES, a, b);
}


#endif // _UNITTYPES_H_